- Jenkinsfile
- pom.xml
Added a JenkinsFile and a Maven profile (named 'ci') that
- checks out the current branch
- replaces '-SNAPSHOT' in the maven poms with '-SNAPSHOT_feature_APPNG_XXXX'
- performs an `mvn clean deploy -Pci -Djavax.xml.accessExternalSchema=all` using the repository `appng-ci-builds`
> APPNG-2145 - Provide an JenkinsFile for CI

- appng-cli/src/main/java/org/appng/cli/commands/subject/CreateSubject.java
- appng-cli/src/test/java/org/appng/cli/commands/subject/CommandCreateSubjectTest.java
CI Status: [![CI Status](https://www.appng.org/jenkins/job/appNG%20CI/job/feature%252FAPPNG-2147/badge/icon)](https://appng.org/jenkins/job/appNG%20CI/job/feature%252FAPPNG-2147/)
> APPNG-2147 support -t, check if user exists

- appng-api/src/main/java/org/appng/api/Request.java
- appng-api/src/main/java/org/appng/api/Webservice.java
- appng-api/src/main/java/org/appng/api/support/ApplicationRequest.java
- appng-api/src/main/java/org/appng/api/support/HttpHeaderUtils.java
- appng-core/src/main/java/org/appng/core/controller/handler/ServiceRequestHandler.java
CI Status: [![CI Status](https://www.appng.org/jenkins/job/appNG%20CI/job/feature%252FAPPNG-2155/badge/icon)](https://appng.org/jenkins/job/appNG%20CI/job/feature%252FAPPNG-2155/)
> APPNG-2155 improve support for HTTP headers

- appng-tools/src/main/java/org/appng/tools/file/PropertyConstantCreator.java
- appng-tools/src/test/java/org/appng/tools/file/PropertyConstantCreatorTest.java
- appng-tools/src/test/resources/Constants.java
- appng-tools/src/test/resources/props.properties
CI Status: [![CI Status](https://www.appng.org/jenkins/job/appNG%20CI/job/bugfix%252FAPPNG-2152/badge/icon)](https://appng.org/jenkins/job/appNG%20CI/job/bugfix%252FAPPNG-2152/)
> APPNG-2152 support/enforce encoding for PropertyConstantCreator

- appng-api/src/main/java/org/appng/api/support/OptionImpl.java
- appng-api/src/test/java/org/appng/api/support/OptionImplTest.java
- appng-api/src/test/java/org/appng/api/support/OptionsImplTest.java
avoid NPE in `OptionImpl.getInteger()`
> APPNG-2153

- appng-core/src/main/java/org/appng/core/model/ThymeleafProcessor.java
- appng-core/src/test/java/org/appng/core/model/ThymeleafProcessorTest.java
- appng-core/src/test/resources/xml/ThymeleafProcessorTest-platform.xml
`hasSort()` must return true for the for sort where order and prio is set
> APPNG-2159 fix hasSort()

- appng-application-bom/pom.xml
- appng-appngizer-maven-plugin/pom.xml
- appng-template-parent/pom.xml
- appng-testsupport/src/main/java/org/appng/testsupport/TestBase.java
- appng-testsupport/src/test/java/org/appng/testsupport/TestBaseTest.java
added `getHandlerMethodArgumentResolver()`
> APPNG-2158

- appng-core/src/main/java/org/appng/core/domain/ResourceImpl.java
- appng-core/src/test/java/org/appng/core/domain/ResourceImplTest.java
Make sure an empty resource also gets a checksum.
> APPNG-2162

- appng-core/src/main/java/org/appng/core/controller/Controller.java
see
https://appng.org/jira/browse/APPNG-2218
> APPNG-2218 make sure session-timeout is set for context

- pom.xml
Run with `mvn clean test sonar:sonar -Psonar`
> APPNG-2228 added sonar profile

- appng-appngizer/src/main/webapp/WEB-INF/appNGizer-servlet.xml
- appng-appngizer/src/test/resources/test-context.xml
- appng-core/src/main/java/org/appng/core/service/CoreService.java
- appng-core/src/main/java/org/appng/core/service/InitializerService.java
- appng-core/src/main/java/org/appng/core/service/PlatformProperties.java
- appng-core/src/main/java/org/appng/core/service/PropertySupport.java
- appng-core/src/main/java/org/appng/core/service/TemplateService.java
- appng-testsupport/src/main/java/org/appng/testsupport/TestBase.java
- mock `site` and `application` in `TestBase`
- `PlatformProperties` is not a bean any more for easier testing
> APPNG-2233 ad missing beans for site and application in TestBase

- appng-cli/src/main/java/org/appng/cli/CliBootstrap.java
- appng-cli/src/test/java/org/appng/cli/CliBootstrapRunner.java
by checking it has already been running before
> APPNG-2238 don't stop HSQL Server accidentally in CLI

- appng-core/src/main/java/org/appng/core/model/ThymeleafProcessor.java
- appng-core/src/test/java/org/appng/core/model/ThymeleafProcessorTest.java
...by taking the first template defined by the output-type
> APPNG-2254 support different output-types

- appng-core/src/main/java/org/appng/core/controller/handler/ServiceRequestHandler.java
- appng-core/src/test/java/org/appng/core/controller/handler/ServiceRequestHandlerTest.java
- return 404 when site or application not found
- return 503 when site is not running
> APPNG-2265 - ServiceRequestHandler should return a more speaking state when site is not available/not started

- appng-core/src/main/java/org/appng/core/model/AbstractRequestProcessor.java
improved logging and return 500 when no visible application is found
> APPNG-2263 improved logging

- appng-core/src/main/java/org/appng/core/service/LdapService.java
..by checking attribute for null
> APPNG-2259 fix possible NPE in LdapService.getMembersOfGroup

- appng-api/src/main/java/org/appng/api/support/field/DateFieldConverter.java
- appng-api/src/test/java/org/appng/api/support/field/DateFieldConverterJodaDateTimeTest.java
- appng-api/src/test/java/org/appng/api/support/field/DateFieldConverterJodaLocalDateTest.java
- appng-api/src/test/java/org/appng/api/support/field/DateFieldConverterJodaLocalDateTimeTest.java
- appng-api/src/test/java/org/appng/api/support/field/DateFieldConverterLocalDateTest.java
- appng-api/src/test/java/org/appng/api/support/field/DateFieldConverterLocalDateTimeTest.java
- appng-api/src/test/java/org/appng/api/support/field/DateFieldConverterOffsetDateTimeTest.java
- appng-api/src/test/java/org/appng/api/support/field/DateFieldConverterTest.java
- appng-api/src/test/java/org/appng/api/support/field/DateFieldConverterZonedDateTimeTest.java
- appng-documentation/src/main/asciidoc/parts/datasources.adoc
improved support for date-fields
> APPNG-2275 improved support for date-fields

- appng-cli/src/main/resources/META-INF/persistence.xml
- appng-core/src/main/java/org/appng/core/domain/JobExecutionRecord.java
- appng-core/src/main/java/org/appng/core/repository/ApplicationRepository.java
- appng-core/src/main/java/org/appng/core/repository/DatabaseConnectionRepository.java
- appng-core/src/main/java/org/appng/core/repository/GroupRepository.java
- appng-core/src/main/java/org/appng/core/repository/JobExecutionRecordRepository.java
- appng-core/src/main/java/org/appng/core/repository/PermissionRepository.java
- appng-core/src/main/java/org/appng/core/repository/PropertyRepository.java
- appng-core/src/main/java/org/appng/core/repository/RepoRepository.java
- appng-core/src/main/java/org/appng/core/repository/ResourceRepository.java
- appng-core/src/main/java/org/appng/core/repository/RoleRepository.java
- appng-core/src/main/java/org/appng/core/repository/SiteApplicationRepository.java
- appng-core/src/main/java/org/appng/core/repository/SiteRepository.java
- appng-core/src/main/java/org/appng/core/repository/SubjectRepository.java
- appng-core/src/main/java/org/appng/core/repository/package-info.java
- appng-core/src/test/java/org/appng/core/repository/JobExecutionRecordRepositoryTest.java
- appng-core/src/test/resources/META-INF/persistence.xml
- intrudoced Entity JobExecutionRecord
- introduced  JobExecutionRecordRepository
- cleaned-up Repositories, removed Transactional(readOnly=true)
> APPNG-2255 create @Entity JobExecutionRecord

- appng-documentation/pom.xml
- appng-documentation/src/main/asciidoc/admin/appngizer.adoc
- appng-documentation/src/main/asciidoc/admin/caching.adoc
- appng-documentation/src/main/asciidoc/admin/cli.adoc
- appng-documentation/src/main/asciidoc/admin/clustering.adoc
- appng-documentation/src/main/asciidoc/admin/setup.adoc
- appng-documentation/src/main/asciidoc/administrationguide.adoc
This should be merged so the platform administration guide can be evolved.
> APPNG-2248 getting started with platform administration guide

- appng-core/src/main/java/org/appng/core/controller/handler/ServiceRequestHandler.java
set header before committing servlet response
> APPNG-2309

- .dockerignore
- Dockerfile
- appng-application/src/main/webapp/WEB-INF/conf/install.list
- docker-compose.yml
> Dockerfile build
